version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - rm -f /etc/apt/sources.list.d/sbt.list
      - apt-get update
      - apt-get install dos2unix
  build:
    commands:
      - mvn --settings settings.xml clean install -e -Dmaven.test.skip -Denv.ARTIFACTORY_USER=$ARTIFACTORY_USER -Denv.ARTIFACTORY_PASSWORD=$ARTIFACTORY_PASSWORD 
      - ls -ltr
      - dos2unix run.sh
      #- cd target
      #- ls -ltr
      - cp -a target ../
      - zip -r artifacts.zip Dockerfile run.sh target
      - cp artifacts.zip ../
artifacts:
  files: 'artifacts.zip'